---
title: "Midterm Project"
author: "Pruthvi Bharadwaj"
date: "11/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(
ggplot2,
rjson,
knitr,
arm,
data.table,
tidyverse,
jsonlite,
rstan,
rstanarm
)
```

## Importing HR attrition dataset

The dataset is in JSON format. Using fromJSON function from jsonlite package to import datafiles


```{r}

path1 <- "/Users/pruthvibharadwaj/Desktop/MA678 - ASM/Midterm Project/HR analytics/WA_Fn-UseC_-HR-Employee-Attrition.csv"

hrdata <- read.csv(path1)
```

```{r}

hrgender <- hrdata %>% group_by(Gender,Attrition) %>% summarise(n=n())

ggplot(hrgender, aes(fill=Attrition,y=n, x=Gender)) + 
    geom_bar(position="fill", stat="identity")

```

```{r}

hrdept <- hrdata %>% group_by(Department,Attrition) %>% summarise(n=n())

ggplot(hrdept, aes(fill=Attrition,y=n, x=Department)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hrtravel <- hrdata %>% group_by(BusinessTravel,Attrition) %>% summarise(n=n())

ggplot(hrtravel, aes(fill=Attrition,y=n, x=BusinessTravel)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hredufield <- hrdata %>% group_by(EducationField,Attrition) %>% summarise(n=n())

ggplot(hredufield, aes(fill=Attrition,y=n, x=EducationField)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hrenvsatisfaction <- hrdata %>% group_by(EnvironmentSatisfaction,Attrition) %>% summarise(n=n())

ggplot(hrenvsatisfaction, aes(fill=Attrition,y=n, x=EnvironmentSatisfaction)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hrjobinv <- hrdata %>% group_by(JobInvolvement,Attrition) %>% summarise(n=n())

ggplot(hrjobinv, aes(fill=Attrition,y=n, x=JobInvolvement)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hrjoblev <- hrdata %>% group_by(JobLevel,Attrition) %>% summarise(n=n())

ggplot(hrjoblev, aes(fill=Attrition,y=n, x=JobLevel)) + 
    geom_bar(position="fill", stat="identity")
```

```{r}
hrmaritalstatus <- hrdata %>% group_by(MaritalStatus,Attrition) %>% summarise(n=n())

ggplot(hrmaritalstatus, aes(fill=Attrition,y=n, x=MaritalStatus)) + 
    geom_bar(position="fill", stat="identity")
```
```{r}
hrnumcompanies <- hrdata %>% group_by(NumCompaniesWorked,Attrition) %>% summarise(n=n())

ggplot(hrnumcompanies, aes(fill=Attrition,y=n, x=NumCompaniesWorked)) + 
    geom_bar(position="fill", stat="identity")
```


## Including Plots

You can also embed plots, for example:

```{r}

hrjobrole <- hrdata %>% group_by(JobRole,Attrition) %>% summarise(n=n())

ggplot(hrjobrole, aes(fill=Attrition,y=n, x=JobRole)) + 
    geom_bar(position="fill", stat="identity")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
